# Change these first
owner: jonassalen # Your GitHub organization or username, where this repository lives
repo: uptime-mechelen # The name of this repository

sites:
  - name: Mechelen
    url: https://www.mechelen.be
  - name: ZBR
    url: https://www.zorgbedrijfrivierenland.be
  - name: Visit
    url: https://visit.mechelen.be/
  - name: Klimaatneutraal
    url: https://klimaatneutraal.mechelen.be/
  - name: Cultuurcentrum
    url: https://cultuurcentrum.mechelen.be/
  - name: UiT in Mechelen
    url: https://uitin.mechelen.be/
  - name: Shoppen
    url: https://shoppenin.mechelen.be/
  - name: Mechelen nieuw
    url: https://mechelen-prod.hosted-temp.com/
  - name: Just goe
    url: https://www.justgoe.be/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-mechelen
  logoUrl: https://assets.vlaanderen.be/image/upload/widgets/mechelen.svg
  name: Uptime Mechelen
  introTitle: "Hoe gaat 't met de websites van Stad Mechelen?"
  introMessage: Deze statuspagina gebruikt **real-time** data van onze websites, te configureren in Github.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.mechelen.be

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
